---
kind: pipeline
name: default
steps:
- name: build
  pull: always
  image: golang:alpine
  commands:
    - "pwd && ls"
    - "cd helloworld"

- name: latest  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    # registry: 
    repo: mirrors2/helloworld
    purge: true
    compress: true
    platforms: linux/amd64,linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    # context: 
    dockerfile: Dockerfile
    tags: latest
  when:
    branch:
    - master
    - alpine/*
    event: 
    - tag

trigger:
  branch:
    - master
  event:
    - pull_request
    - push